#!/bin/sh
mvn clean package \
	&& cd target && unzip unifiedpush-migrator-1.1.0.Fina-dist.zip \
	&& cd unifiedpush-migrator-1.1.0.Final/ \
	&& cp ../../liquibase-mysql-example.properties liquibase.properties \
	&& mkdir liquibase && bin/ups-migrator --logLevel=INFO update
