/*
 * Copyright 2018 JBoss by Red Hat.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jboss.aerogear.unifiedpush.api;

/**
 *
 * @author Mohammad-Hossein Jamali
 */
public class WebInstallation extends BaseModel {
    private static final long serialVersionUID = 7177135978544758236L;
    
    private Installation installation;
    private String endpoint; 
    private String key;
    private String auth;

    public Installation getInstallation() {
        return installation;
    }

    /**
     * 
     * @param installation the installation for which extra information (endpoint, key and auth) are persisted.
     */    
    public void setInstallation(Installation installation) {
        this.installation = installation;
    }
    
    public String getEndpoint() {
        return endpoint;
    }

    /**
     * 
     * @param endpoint the full endpoint path which is generated by browser when subscribe() function is called 
     */
    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint;
    }

    public String getKey() {
        return key;
    }

    /**
     * 
     * @param key the public key of subscription object
     */
    public void setKey(String key) {
        this.key = key;
    }

    public String getAuth() {
        return auth;
    }

    /**
     * 
     * @param auth the user auth of subscription object
     */
    public void setAuth(String auth) {
        this.auth = auth;
    }
        
}
